# Generated by Django 2.2.7 on 2019-11-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfor',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='userinfor',
            name='username',
        ),
        migrations.AddField(
            model_name='userinfor',
            name='dateHired',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userinfor',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userinfor',
            name='phoneNumber',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userinfor',
            name='position',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userinfor',
            name='salary',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
