# Generated by Django 2.2.7 on 2019-11-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20191123_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfor',
            old_name='dateHired',
            new_name='dh',
        ),
        migrations.RenameField(
            model_name='userinfor',
            old_name='email',
            new_name='em',
        ),
        migrations.RenameField(
            model_name='userinfor',
            old_name='name',
            new_name='nm',
        ),
        migrations.RenameField(
            model_name='userinfor',
            old_name='phoneNumber',
            new_name='pn',
        ),
        migrations.RenameField(
            model_name='userinfor',
            old_name='position',
            new_name='pos',
        ),
        migrations.RenameField(
            model_name='userinfor',
            old_name='salary',
            new_name='sl',
        ),
    ]
